In [ ]:
import os
import pandas as pd
pd.set_option('display.max_columns', None)
from gpt_utils import *

%load_ext autoreload
%autoreload 2

In [2]:
!source setup_env.sh

Requirement already satisfied: annotated-types==0.6.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: anyio==4.2.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (4.2.0)
Requirement already satisfied: appnope==0.1.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.1.3)
Requirement already satisfied: argon2-cffi-bindings==21.2.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (21.2.0)
Requirement already satisfied: arrow==1.3.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: asttokens==2.4.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.4.1)
Requirement already satisfied: async-lru==2.0.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (2.0.4)
Requirement already satisfied: attrs==23.2.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (23.2.0)
Requirement already satisfied: Babel==2.14.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (2.14.0)
Requirement already satisfied: beautifulsoup4==4.12.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (4.12.3)
Requirement already satisfied: bleach==6.1.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (6.1.0)
Requirement already satisfied: certifi==2023.11.17 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2023.11.17)
Requirement already satisfied: cffi==1.16.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.16.0)
Requirement already satisfied: charset-normalizer==3.3.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (3.3.2)
Requirement already satisfied: comm==0.2.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (0.2.1)
Requirement already satisfied: debugpy==1.8.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (1.8.0)
Requirement already satisfied: decorator==5.1.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (5.1.1)
Requirement already satisfied: defusedxml==0.7.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (0.7.1)
Requirement already satisfied: distro==1.9.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (1.9.0)
Requirement already satisfied: et-xmlfile==1.1.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (1.1.0)
Requirement already satisfied: exceptiongroup==1.2.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (1.2.2)
Requirement already satisfied: executing==2.0.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 22)) (2.0.1)
Requirement already satisfied: fastjsonschema==2.19.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 23)) (2.19.1)
Requirement already satisfied: filelock==3.13.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 24)) (3.13.1)
Requirement already satisfied: fqdn==1.5.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 25)) (1.5.1)
Requirement already satisfied: fsspec==2023.12.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 26)) (2023.12.2)
Requirement already satisfied: h11==0.16.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 27)) (0.16.0)
Requirement already satisfied: httpcore==1.0.9 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 28)) (1.0.9)
Requirement already satisfied: httpx==0.26.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 29)) (0.26.0)
Requirement already satisfied: idna==3.6 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 30)) (3.6)
Requirement already satisfied: jedi==0.19.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 31)) (0.19.1)
Requirement already satisfied: Jinja2==3.1.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 32)) (3.1.3)
Requirement already satisfied: joblib==1.3.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 33)) (1.3.2)
Requirement already satisfied: json5==0.9.14 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 34)) (0.9.14)
Requirement already satisfied: jsonpointer==2.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 35)) (2.4)
Requirement already satisfied: jsonschema-specifications==2023.12.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 36)) (2023.12.1)
Requirement already satisfied: jupyter_client==8.6.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 37)) (8.6.0)
Requirement already satisfied: jupyter_core==5.7.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 38)) (5.7.1)
Requirement already satisfied: jupyter_server_terminals==0.5.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 39)) (0.5.1)
Requirement already satisfied: jupyterlab_pygments==0.3.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 40)) (0.3.0)
Requirement already satisfied: krippendorff==0.6.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 41)) (0.6.1)
Requirement already satisfied: MarkupSafe==2.1.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 42)) (2.1.4)
Requirement already satisfied: matplotlib-inline==0.1.6 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 43)) (0.1.6)
Requirement already satisfied: mistune==3.0.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 44)) (3.0.2)
Requirement already satisfied: mpmath==1.3.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 45)) (1.3.0)
Requirement already satisfied: nest-asyncio==1.5.9 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 46)) (1.5.9)
Requirement already satisfied: networkx==3.2.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 47)) (3.2.1)
Requirement already satisfied: numpy==1.26.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 48)) (1.26.3)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 49)) (12.6.4.1)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 50)) (12.6.80)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 51)) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 52)) (12.6.77)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 53)) (9.5.1.17)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 54)) (11.3.0.4)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 55)) (1.11.1.6)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 56)) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 57)) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 58)) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 59)) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 60)) (2.26.2)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 61)) (12.6.85)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 62)) (12.6.77)
Requirement already satisfied: openpyxl==3.1.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 63)) (3.1.2)
Requirement already satisfied: overrides==7.6.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 64)) (7.6.0)
Requirement already satisfied: packaging==23.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 65)) (23.2)
Requirement already satisfied: pandas==2.1.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 66)) (2.1.4)
Requirement already satisfied: pandocfilters==1.5.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 67)) (1.5.1)
Requirement already satisfied: parso==0.8.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 68)) (0.8.3)
Requirement already satisfied: pexpect==4.9.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 69)) (4.9.0)
Requirement already satisfied: platformdirs==4.1.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 70)) (4.1.0)
Requirement already satisfied: prometheus-client==0.19.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 71)) (0.19.0)
Requirement already satisfied: prompt-toolkit==3.0.43 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 72)) (3.0.43)
Requirement already satisfied: psutil==5.9.8 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 73)) (5.9.8)
Requirement already satisfied: ptyprocess==0.7.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 74)) (0.7.0)
Requirement already satisfied: pure-eval==0.2.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 75)) (0.2.2)
Requirement already satisfied: pycparser==2.21 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 76)) (2.21)
Requirement already satisfied: pydantic==2.5.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 77)) (2.5.3)
Requirement already satisfied: pydantic_core==2.14.6 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 78)) (2.14.6)
Requirement already satisfied: Pygments==2.17.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 79)) (2.17.2)
Requirement already satisfied: python-dateutil==2.8.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 80)) (2.8.2)
Requirement already satisfied: python-json-logger==2.0.7 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 81)) (2.0.7)
Requirement already satisfied: pytz==2023.3.post1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 82)) (2023.3.post1)
Requirement already satisfied: PyYAML==6.0.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 83)) (6.0.1)
Requirement already satisfied: pyzmq==25.1.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 84)) (25.1.2)
Requirement already satisfied: referencing==0.32.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 85)) (0.32.1)
Requirement already satisfied: requests==2.31.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 86)) (2.31.0)
Requirement already satisfied: rfc3339-validator==0.1.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 87)) (0.1.4)
Requirement already satisfied: rfc3986-validator==0.1.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 88)) (0.1.1)
Requirement already satisfied: rpds-py==0.17.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 89)) (0.17.1)
Requirement already satisfied: scikit-learn==1.3.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 90)) (1.3.2)
Requirement already satisfied: scipy==1.11.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 91)) (1.11.4)
Requirement already satisfied: Send2Trash==1.8.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 92)) (1.8.2)
Requirement already satisfied: six==1.16.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 93)) (1.16.0)
Requirement already satisfied: sniffio==1.3.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 94)) (1.3.0)
Requirement already satisfied: soupsieve==2.5 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 95)) (2.5)
Requirement already satisfied: stack-data==0.6.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 96)) (0.6.3)
Requirement already satisfied: sympy==1.13.3 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 97)) (1.13.3)
Requirement already satisfied: terminado==0.18.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 98)) (0.18.0)
Requirement already satisfied: threadpoolctl==3.2.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 99)) (3.2.0)
Requirement already satisfied: tinycss2==1.2.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 100)) (1.2.1)
Requirement already satisfied: tomli==2.2.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 101)) (2.2.1)
Requirement already satisfied: torch==2.7.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 102)) (2.7.0)
Collecting tornado==6.4
  Using cached tornado-6.4-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
Requirement already satisfied: tqdm==4.66.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 104)) (4.66.1)
Requirement already satisfied: traitlets==5.14.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 105)) (5.14.1)
Requirement already satisfied: triton==3.3.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 106)) (3.3.0)
Requirement already satisfied: types-python-dateutil==2.8.19.20240106 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 107)) (2.8.19.20240106)
Requirement already satisfied: typing_extensions==4.13.2 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 108)) (4.13.2)
Requirement already satisfied: tzdata==2023.4 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 109)) (2023.4)
Requirement already satisfied: uri-template==1.3.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 110)) (1.3.0)
Requirement already satisfied: urllib3==2.1.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 111)) (2.1.0)
Requirement already satisfied: wcwidth==0.2.13 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 112)) (0.2.13)
Requirement already satisfied: webcolors==1.13 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 113)) (1.13)
Requirement already satisfied: webencodings==0.5.1 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 114)) (0.5.1)
Requirement already satisfied: websocket-client==1.7.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from -r requirements.txt (line 115)) (1.7.0)
Requirement already satisfied: setuptools>=40.8.0 in ./emotion_metric_venv/lib/python3.10/site-packages (from triton==3.3.0->-r requirements.txt (line 106)) (65.5.0)
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 6.5.1
    Uninstalling tornado-6.5.1:
      Successfully uninstalled tornado-6.5.1
Successfully installed tornado-6.4

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

### GoEmotions Classification

In [3]:
goemotions_df = get_dataset('data/goemotions_test_50.csv')
goemotions_df = SanitizeGoEmotionsDataFrame(goemotions_df)
goemotions_samples = goemotions_df.sample(10, random_state=10).reset_index(); goemotions_samples

,index,id,text,label,human_label
0,37,ee2k9xt,Hey that's a thought! Maybe we need [NAME] to ...,27,neutral
1,23,edr2ac7,"Well, there's cubs and otters too.",27,neutral
2,44,ef0puf0,A surprise turn of events! I'm so glad you hea...,"17,26","joy,surprise"
3,42,ee1veao,I think the fan base is mostly past that at th...,27,neutral
4,47,efh4i9q,This is honestly the cherry on top of the cake...,1,amusement
5,20,eeyh5zd,"I know you're joking, but there are people her...",1,amusement
6,3,eelgwd1,"I didn't know that, thank you for teaching me ...",15,gratitude
7,30,edlt8ec,NJ has zero of their own picks from the 2010 d...,27,neutral
8,7,ef0ec3b,100%! Congrats on your job too!,15,gratitude
9,6,efdbh17,You’re welcome,15,gratitude

In [4]:
goemotions_classification_4 = GetGptAnnotationWithRetriesForGoEmotionsClassification(goemotions_samples, DEPLOYMENT_NAME_4, max_retries=5, verbose=True)

OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.

In [11]:
goemotions_classification_35 = GetGptAnnotationWithRetriesForGoEmotionsClassification(goemotions_samples, DEPLOYMENT_NAME_35, max_retries=5, verbose=True)

Sample#0: Text is 'I live here! Apparently I need to be keeping my eyes open.'
	Attempt#1: raw  <neutral> sanitized to <neutral> (PASSED)
Sample#1: Text is 'What GDP growth? The one that barely broke 3-4% since 1984 and has dwindled to 1-2% to 0 to negative 1%?'
	Attempt#1: raw  <disappointment, annoyance> sanitized to <annoyance,disappointment> (PASSED)
Sample#2: Text is 'I have trophy jeans and a trophy bra! Although RIP my boobs because they were the one thing I liked about my body back then :)'
	Attempt#1: raw  <amusement, disapproval> sanitized to <amusement,disapproval> (PASSED)
Sample#3: Text is '[NAME] boxing gym in Ross is super inviting to everyone! It's a legit boxing club that is also friendly to folks just looking for a workout.'
	Attempt#1: raw  <admiration, approval> sanitized to <admiration,approval> (PASSED)
Sample#4: Text is 'So can we all collectively accept that [NAME] has a high placement for this week? Okay thank you'
	Attempt#1: raw  <approval, neutral> sanitized to <approval,neutral> (PASSED)
Sample#5: Text is 'Yep. He also said it’d happen on a Manbij patrol'
	Attempt#1: raw  <neutral> sanitized to <neutral> (PASSED)
Sample#6: Text is 'Laughing at "indoctrinated by traditional values". Good luck in life.'
	Attempt#1: raw  <amusement, annoyance> sanitized to <amusement,annoyance> (PASSED)
Sample#7: Text is 'Ok, thats my thinking too. If [NAME] really only gets 180 anyone who didn't make that deal (like us) is pretty dang foolish.'
	Attempt#1: raw  <disapproval, annoyance, neutral> sanitized to <annoyance,disapproval,neutral> (PASSED)
Sample#8: Text is 'Are you daft ... ? That is and always has been the proposal. [NAME] don't listen and don't care though. Fucking dumbass.'
	Attempt#1: raw  <anger> sanitized to <anger> (PASSED)
Sample#9: Text is 'What kind of behaviour is considered unattractive? I'm pretty clueless when it comes to dating.'
	Attempt#1: raw  <confusion, curiosity, neutral> sanitized to <confusion,curiosity,neutral> (PASSED)

In [12]:
goemotions_samples['classification_4'] = goemotions_classification_4
goemotions_samples['classification_35'] = goemotions_classification_35
goemotions_samples

,index,id,text,human_label,classification_4,classification_35
0,330,ef8avyw,I live here! Apparently I need to be keeping m...,neutral,surprise,neutral
1,1832,ef6xdiq,What GDP growth? The one that barely broke 3-4...,curiosity,"annoyance,disappointment","annoyance,disappointment"
2,3209,ee5i0j2,I have trophy jeans and a trophy bra! Although...,"disappointment,neutral","amusement,sadness","amusement,disapproval"
3,3381,edpw2z1,[NAME] boxing gym in Ross is super inviting to...,admiration,"admiration,approval","admiration,approval"
4,3395,edwe3w0,So can we all collectively accept that [NAME] ...,gratitude,"approval,optimism","approval,neutral"
5,2030,ee8kh9s,Yep. He also said it’d happen on a Manbij patrol,"approval,neutral",neutral,neutral
6,3575,eeabdmg,"Laughing at ""indoctrinated by traditional valu...","annoyance,optimism","amusement,disapproval","amusement,annoyance"
7,3799,eevggs1,"Ok, thats my thinking too. If [NAME] really on...","annoyance,disappointment","annoyance,disappointment","annoyance,disapproval,neutral"
8,1978,eczkjma,Are you daft ... ? That is and always has been...,anger,"anger,annoyance,disapproval",anger
9,3475,edkh28y,What kind of behaviour is considered unattract...,confusion,curiosity,"confusion,curiosity,neutral"

In [19]:
goemotions_samples.to_csv('test.csv')

### Emobank Regression

In [13]:
emobank_df = get_dataset('data/emobank_reader_test.csv')

In [14]:
emobank_df['weight'] = abs(emobank_df['V'] - 3) + abs(emobank_df['A'] - 3)
emobank_samples = emobank_df.sample(10, weights = emobank_df.weight, random_state=SEED); emobank_samples

,Unnamed: 0,id,text,V,A,weight
392,392,Nathans_Bylichka_47387_47415,“That was very kind of her.”,4.0,3.0,1.0
949,949,sucker_2143_2226,I read that article in the Times and IMMEDIATE...,2.6,3.8,1.2
734,734,captured_moments_19437_19659,"The next evening, she arrived with a stack of ...",3.4,2.8,0.6
570,570,The_Black_Willow_6754_6832,There simply is no audience for fairy tales – ...,2.4,3.0,0.6
172,172,Bartok_11929_12054,"As Example 10 shows, the chords are more-or-le...",3.2,2.8,0.4
57,57,116CUL034_979_1118,A Providers Council and a Youth Coalition are ...,3.8,3.2,1.0
865,865,hotel-california_18330_18380,"I guess we all figured, he knew what he was do...",3.2,3.2,0.4
574,574,The_Black_Willow_8763_8866,The reply came from above him and Allan turned...,3.2,3.0,0.2
705,705,audubon2_2158_2253,I’ve had a look at the magazine’s upcoming sub...,3.2,3.2,0.4
16,16,110CYL200_1611_1668,"Some are blind, deaf or have other physical di...",2.0,3.0,1.0

In [15]:
emobank_regression_4 = GetGptAnnotationWithRetriesForEmoBankRegression(emobank_samples, DEPLOYMENT_NAME_4, max_retries=2, verbose=True)

Sample#392: Text is '“That was very kind of her.”'
	Attempt#1: raw  <5> sanitized to <5> (PASSED)
Sample#949: Text is 'I read that article in the Times and IMMEDIATELY thought it was going to be a hoax.'
	Attempt#1: raw  <2> sanitized to <2> (PASSED)
Sample#734: Text is 'The next evening, she arrived with a stack of glistening stopboxes containing sushi, sashimi, oysters in their shells, and Terran vegetables fresh plucked from their hydroponic beds.'
	Attempt#1: raw  <5> sanitized to <5> (PASSED)
Sample#570: Text is 'There simply is no audience for fairy tales – no literate audience, at least."'
	Attempt#1: raw  <2> sanitized to <2> (PASSED)
Sample#172: Text is 'As Example 10 shows, the chords are more-or-less in duple meter (4/8 and 2/8) with one “hiccup” occurring in the 5/8 measure.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)
Sample#57: Text is 'A Providers Council and a Youth Coalition are building relationships that will hopefully bear great fruit in the years to come.'
	Attempt#1: raw  <5> sanitized to <5> (PASSED)
Sample#865: Text is 'I guess we all figured, he knew what he was doing.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)
Sample#574: Text is 'The reply came from above him and Allan turned to see his friend reclining in the fork of a great tree.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)
Sample#705: Text is 'I’ve had a look at the magazine’s upcoming subjects and I can tell you the best is yet to come.'
	Attempt#1: raw  <5> sanitized to <5> (PASSED)
Sample#16: Text is 'Some are blind, deaf or have other physical disabilities.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)

In [16]:
emobank_regression_35 = GetGptAnnotationWithRetriesForEmoBankRegression(emobank_samples, DEPLOYMENT_NAME_35, max_retries=2, verbose=True)

Sample#392: Text is '“That was very kind of her.”'
	Attempt#1: raw  <5> sanitized to <5> (PASSED)
Sample#949: Text is 'I read that article in the Times and IMMEDIATELY thought it was going to be a hoax.'
	Attempt#1: raw  <2> sanitized to <2> (PASSED)
Sample#734: Text is 'The next evening, she arrived with a stack of glistening stopboxes containing sushi, sashimi, oysters in their shells, and Terran vegetables fresh plucked from their hydroponic beds.'
	Attempt#1: raw  <4> sanitized to <4> (PASSED)
Sample#570: Text is 'There simply is no audience for fairy tales – no literate audience, at least."'
	Attempt#1: raw  <2> sanitized to <2> (PASSED)
Sample#172: Text is 'As Example 10 shows, the chords are more-or-less in duple meter (4/8 and 2/8) with one “hiccup” occurring in the 5/8 measure.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)
Sample#57: Text is 'A Providers Council and a Youth Coalition are building relationships that will hopefully bear great fruit in the years to come.'
	Attempt#1: raw  <4> sanitized to <4> (PASSED)
Sample#865: Text is 'I guess we all figured, he knew what he was doing.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)
Sample#574: Text is 'The reply came from above him and Allan turned to see his friend reclining in the fork of a great tree.'
	Attempt#1: raw  <3> sanitized to <3> (PASSED)
Sample#705: Text is 'I’ve had a look at the magazine’s upcoming subjects and I can tell you the best is yet to come.'
	Attempt#1: raw  <5> sanitized to <5> (PASSED)
Sample#16: Text is 'Some are blind, deaf or have other physical disabilities.'
	Attempt#1: raw  <2> sanitized to <2> (PASSED)

In [17]:
emobank_samples['regression_4'] = emobank_regression_4
emobank_samples['regression_35'] = emobank_regression_35
emobank_samples

,Unnamed: 0,id,text,V,A,weight,regression_4,regression_35
392,392,Nathans_Bylichka_47387_47415,“That was very kind of her.”,4.0,3.0,1.0,5,5
949,949,sucker_2143_2226,I read that article in the Times and IMMEDIATE...,2.6,3.8,1.2,2,2
734,734,captured_moments_19437_19659,"The next evening, she arrived with a stack of ...",3.4,2.8,0.6,5,4
570,570,The_Black_Willow_6754_6832,There simply is no audience for fairy tales – ...,2.4,3.0,0.6,2,2
172,172,Bartok_11929_12054,"As Example 10 shows, the chords are more-or-le...",3.2,2.8,0.4,3,3
57,57,116CUL034_979_1118,A Providers Council and a Youth Coalition are ...,3.8,3.2,1.0,5,4
865,865,hotel-california_18330_18380,"I guess we all figured, he knew what he was do...",3.2,3.2,0.4,3,3
574,574,The_Black_Willow_8763_8866,The reply came from above him and Allan turned...,3.2,3.0,0.2,3,3
705,705,audubon2_2158_2253,I’ve had a look at the magazine’s upcoming sub...,3.2,3.2,0.4,5,5
16,16,110CYL200_1611_1668,"Some are blind, deaf or have other physical di...",2.0,3.0,1.0,3,2